tests/mypy/mypy_function_wrapper_cls_t3.py:26: error: Argument 2 to "FunctionWrapper" has incompatible type "Callable[[str, Any, tuple[Any, ...], dict[str, Any]], Any]"; expected "Callable[[Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str] | Callable[[type[Any], Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str] | Callable[[Any, Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
