tests/mypy/mypy_function_wrapper_cls_t6.py:19: error: Argument 2 to "FunctionWrapper" has incompatible type "str"; expected "Callable[[Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str] | Callable[[type[Any], Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str] | Callable[[Any, Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str]"  [arg-type]
tests/mypy/mypy_function_wrapper_cls_t6.py:20: error: Argument 2 to "FunctionWrapper" has incompatible type "None"; expected "Callable[[Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str] | Callable[[type[Any], Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str] | Callable[[Any, Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
